### ISSUE TITLE
New alphabet - b32 for user input codes

### ISSUE THREAD

**Issue by jotavemonte** [bnlucas/obfuskey#10]
I deal with some misconceptions of characters from users when they need to input these codes. The chars are  '1', 'I', '0', 'O'.
I think this may be a pretty common use case. If the obfuskey had a b32 alphabet, it would be a good way to handle this kind of problem.

The proposed b32 alphabet is '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'

**Comment by nlucasgp** [comment]
Thanks for the suggestion! I will look into it when I have a free minute. For now, you can specify any alphabet you'd like using `Obfuskey('012abc')`, the bases are there for easy access to specific ones.

**Comment by nlucasgp** [comment]
I noticed there's no mention of this in the readme, I'll get that updated as well.

**Comment by jotavemonte** [comment]
Thank you!
Awesome package, btw
